/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function opSpawn(cmd: string, args: Array<string>, exitCb: (err: Error | null, arg0: number, arg1: number) => any, stdoutCb: (err: Error | null, arg: Buffer | undefined | null) => any, stderrCb: (err: Error | null, arg: Buffer | undefined | null) => any): Promise<number>
